[package]
name = "rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tungstenite = {version = "0.21", features = ["native-tls"]}
url = "2.2.2"
tokio = { version = "1.14.0", features = ["full"] }
futures-util = "0.3.21"
tokio-tungstenite = {version = "0.21", features = ["native-tls"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-peers-protocol = "0.3"
webrtc = "0.10.1"
tokio-stream = "0.1.14"
log = "0.4.21"
simplelog = "0.12.2"
